In [76]:
import pdfplumber
pdf=pdfplumber.open("044002007111_22865083.pdf")
page = pdf.pages[0]   # 第一页的信息
text = page.extract_text() ##读取pdf文本信息
print(text)

2021  09  10
1*39<91*262+29>8+906>5723*3
91440604MA54W5083J *84039-*2<+19741877+<8>4526
895+04808>>+/527297><91+-26
02*>8+6130/90>+797538-4*74-
¥248.67 ¥32.33
¥281.00
91440600724779144R

In [72]:
 for t in table:
        # 得到的table是嵌套list类型，转化成DataFrame更加方便查看和分析
        df = pd.DataFrame(t[1:], columns=t[0])
        print(df)

     91440604MA54W5083J      NaN   NaN   NaN   NaN        \
0                  None                             None
1                  None  ¥281.00  None  None  None  None
2    91440600724779144R     None  None  None  None

  1*39<91*262+29>8+906>5723*3\n*84039-*2<+19741877+<8>4526\n895+04808>>+/527297><91+-26\n02*>8+6130/90>+797538-4*74-  \
0                                               None
1                                               None
2

       NaN   NaN     NaN
0  ¥248.67        ¥32.33
1     None  None    None
2     None  None    None

In [75]:
df = pd.DataFrame(table[1:], columns=table[0])
df

Empty DataFrame
Columns: [(, , , ), (91440604MA54W5083J, nan, nan, 91440600724779144R), (nan, , ¥281.00, nan), (nan, , nan, nan), (nan, , nan, nan), (nan, , nan, nan), (, nan, nan, ), (1*39<91*262+29>8+906>5723*3
*84039-*2<+19741877+<8>4526
895+04808>>+/527297><91+-26
02*>8+6130/90>+797538-4*74-, nan, nan, ), (nan, ¥248.67, nan, nan), (nan, , nan, nan), (nan, ¥32.33, nan, nan)]
Index: []

In [5]:
import pdfplumber
# 读取pdf文件，保存为pdf实例
pdf =  pdfplumber.open("044002007111_22865083.pdf") 
# 访问第二页
first_page = pdf.pages[0]
# 自动读取表格信息，返回列表
table = first_page.extract_table()
table

[['购\n买\n方',
  '名        称:佛山市数蟒信息技术有限公司\n纳税人识别号:91440604MA54W5083J\n地 址、电 话:\n开户行及账号:',
  None,
  None,
  None,
  None,
  '密\n码\n区',
  '1*39<91*262+29>8+906>5723*3\n*84039-*2<+19741877+<8>4526\n895+04808>>+/527297><91+-26\n02*>8+6130/90>+797538-4*74-',
  None,
  None,
  None],
 ['货物或应税劳务、服务名称     \n*汽油*92号车用汽油(ⅥA)\n合       计',
  None,
  '规格型号 \n92号',
  '单位\n升',
  '数 量\n40.60693642',
  '单 价\n6.1238306',
  None,
  None,
  '金  额  \n248.67\n¥248.67',
  '税率\n13%',
  '税    额\n32.33\n¥32.33'],
 ['价税合计(大写)',
  None,
  '贰佰捌拾壹圆整 (小写)¥281.00',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None],
 ['销\n售\n方',
  '名        称:中国石化销售股份有限公司广东佛山石油分公司\n纳税人识别号:91440600724779144R\n地 址、电 话:佛山市禅城区卫国西路24号 0757-83357924\n开户行及账号:中国工商银行佛山汾江支行 2013028729200076015',
  None,
  None,
  None,
  None,
  '备\n注',
  '',
  None,
  None,
  None]]

In [2]:
import camelot
tables = camelot.read_pdf("044002007111_22865083.pdf")
tables

In [4]:
tables[0].df

,0,1,2,3,4,5,6,7,8,9,10,11
0,购\n买\n方,名 称:\n佛山市数蟒信息技术有限公司\n纳税人识别号:\n91440604M...,,,,,,密\n码\n区,1*39<91*262+29>8+906>5723*3\n*84039-*2<+197418...,,,
1,货物或应税劳务、服务名称 规格型号 单位\n*汽油*92号车用汽油(ⅥA)\...,,,92号,升,数 量\n40.60693642,单 价\n6.1238306,,,金 额\n248.67\n¥248.67,税率 税 额\n13%,32.33\n¥32.33
2,价税合计(大写),,,(小写)\n贰佰捌拾壹圆整\n¥281.00,,,,,,,,
3,售 方\n销,,中国石化销售股份有限公司广东佛山石油分公司\n名 称:\n纳税人识别号:\n9...,,,,,备\n注,,,,

In [34]:
tables = camelot.read_pdf('044002007111_22865083.pdf', strip_text='\n')
tables[0].df

,0,1,2,3,4,5,6,7,8,9,10,11
0,购买方,名 称:佛山市数蟒信息技术有限公司纳税人识别号:91440604MA54W50...,,,,,,密码区,1*39<91*262+29>8+906>5723*3*84039-*2<+19741877...,,,
1,货物或应税劳务、服务名称 规格型号 单位*汽油*92号车用汽油(ⅥA)合 ...,,,92号,升,数 量40.60693642,单 价6.1238306,,,金 额248.67¥248.67,税率 税 额13%,32.33¥32.33
2,价税合计(大写),,,(小写)贰佰捌拾壹圆整¥281.00,,,,,,,,
3,售 方销,,中国石化销售股份有限公司广东佛山石油分公司名 称:纳税人识别号:9144060...,,,,,备注,,,,

In [17]:
tables = camelot.read_pdf('044002007111_22865083.pdf',shift_text=[''])##折分合并单元格
tables[0].df

,0,1,2,3,4,5,6,7,8,9,10,11
0,购\n买\n方,,名 称:\n纳税人识别号:\n地 址、电 话:\n开户行及账号:,佛山市数蟒信息技术有限公司\n91440604MA54W5083J,,,,密\n码\n区,,1*39<91*262+29>8+906>5723*3\n*84039-*2<+197418...,,
1,,*汽油*92号车用汽油(ⅥA),货物或应税劳务、服务名称 规格型号 单位\n合 计,92号,升,数 量\n40.60693642,,单 价,6.1238306,金 额\n248.67\n¥248.67,税率 税 额\n13%,32.33\n¥32.33
2,,,价税合计(大写),,贰佰捌拾壹圆整,,,,,(小写),¥281.00,
3,售 方\n销,,名 称:\n纳税人识别号:\n地 址、电 话:\n开户行及账号:,中国石化销售股份有限公司广东佛山石油分公司\n91440600724779144R\n佛山市...,,,,备\n注,,,,

In [41]:
tables = camelot.read_pdf('044002007111_22865083.pdf',shift_text=[''],strip_text='\n')
tables[0].df
df03=tables[0].df
df03

,0,1,2,3,4,5,6,7,8,9,10,11
0,购买方,,名 称:纳税人识别号:地 址、电 话:开户行及账号:,佛山市数蟒信息技术有限公司91440604MA54W5083J,,,,密码区,,1*39<91*262+29>8+906>5723*3*84039-*2<+19741877...,,
1,,*汽油*92号车用汽油(ⅥA),货物或应税劳务、服务名称 规格型号 单位合 计,92号,升,数 量40.60693642,,单 价,6.1238306,金 额248.67¥248.67,税率 税 额13%,32.33¥32.33
2,,,价税合计(大写),,贰佰捌拾壹圆整,,,,,(小写),¥281.00,
3,售 方销,,名 称:纳税人识别号:地 址、电 话:开户行及账号:,中国石化销售股份有限公司广东佛山石油分公司91440600724779144R佛山市禅城区卫...,,,,备注,,,,

In [12]:
df02=tables[0].parsing_report ##查看准确率
df02

{'accuracy': 78.64, 'whitespace': 52.08, 'order': 1, 'page': 1}

In [167]:
##批量读取发票，然后汇总成一个CSV文件
import camelot
import pandas as pd 
import os
##定义文件夹位置
directoryPath = r'E:\py读取pdf发票汇总'##如果改为=os.getcwd()表示当前文件夹
os.chdir(directoryPath)
print(os.listdir())##列取该文件夹下所有文件名称
folderList = os.listdir(directoryPath)
for folders, sub_folders, file in os.walk(directoryPath):  ##所有文件的路径
    for name in file:  ##定义所需文件名
        if name.endswith(".pdf"):  ##如果文件名是以.pdf结束的话
            filename = os.path.join(folders,name) ##定义这条路径
            print(filename)##输出文件路径
            print(name)##输出文件名
            tables = camelot.read_pdf(filename,shift_text=[''],strip_text='\n')##读取pdf文件，
            df01= tables[0].df##转换为DF表格
            #df01.to_excel('{name}.xlsx',sheet_name=name)
            df01.to_csv('foo2.csv',mode="a",encoding="utf_8_sig")##保存为CSV格式，以直接使参数mode='a’实现每个表追加数据，

['.ipynb_checkpoints', '182A2100', '22865083.pdf', '22865084.pdf', 'foo2.csv', 'output.xlsx', 'python读取PDF.ipynb', 'wsave.xlsx', '{name}.xlsx', '发票整理.xlsx', '发票汇总.xlsx']
E:\py读取pdf发票汇总\22865083.pdf
22865083.pdf
E:\py读取pdf发票汇总\22865084.pdf
22865084.pdf

In [170]:
tables = camelot.read_pdf(filename,layout_kwargs={'detect_vertical': False},shift_text=[''],strip_text='\n')
tables[0].df

,0,1,2,3,4,5,6,7,8,9,10,11
0,购买方,,名 称:纳税人识别号:地 址、电 话:开户行及账号:,佛山市数蟒信息技术有限公司91440604MA54W5083J,,,,密码区,,1*39<91*262+29>8+906>5723*3*84039-*2<+19741877...,,
1,,*汽油*92号车用汽油(ⅥA),货物或应税劳务、服务名称 规格型号 单位合 计,92号,升,数 量40.60693642,,单 价,6.1238306,金 额248.67¥248.67,税率 税 额13%,32.33¥32.33
2,,,价税合计(大写),,贰佰捌拾壹圆整,,,,,(小写),¥281.00,
3,销售方,,名 称:纳税人识别号:地 址、电 话:开户行及账号:,中国石化销售股份有限公司广东佛山石油分公司91440600724779144R佛山市禅城区卫...,,,,备注,,,,